# Generated by Django 3.0.2 on 2020-02-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_executives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoing_delivery',
            old_name='date_joined',
            new_name='date_started',
        ),
        migrations.RemoveField(
            model_name='ongoing_delivery',
            name='phone_number',
        ),
    ]
