# Generated by Django 3.0.2 on 2020-02-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_executives', '0002_auto_20200206_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver_executive',
            name='qr_code_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
