# Generated by Django 3.0.2 on 2020-01-21 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='No Date Provided', max_length=24)),
                ('time', models.CharField(default='No Time Provided', max_length=24)),
                ('on_going', models.BooleanField(default=True)),
                ('completed_status', models.CharField(default='', max_length=50)),
                ('ordered_data', models.CharField(default='', max_length=254)),
                ('created_date', models.DateTimeField(editable=False)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tracker Details',
            },
        ),
    ]
