# Generated by Django 2.2.2 on 2019-12-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191222_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_dashboard',
            name='overflown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_dashboard',
            name='ordered_dates',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
