# Generated by Django 2.2.2 on 2019-12-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20191222_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overflown_Orders_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overflown_data', models.CharField(default='', max_length=21000)),
                ('date_created', models.DateTimeField(editable=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Overflown Orders Data',
            },
        ),
        migrations.CreateModel(
            name='Old_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='', max_length=21000)),
                ('date_created', models.DateTimeField(editable=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Old data of orders',
            },
        ),
    ]
