# Generated by Django 3.0.2 on 2020-01-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200123_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='current_order_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
