# Generated by Django 3.0.2 on 2020-01-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200123_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='other_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plans',
            name='regular_count',
            field=models.IntegerField(default=0),
        ),
    ]
