# Generated by Django 2.2.2 on 2019-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
                ('date_sent', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_subscribed', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
