# Generated by Django 3.0.2 on 2020-01-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name_plural': 'Plans'},
        ),
    ]
