# Generated by Django 3.0.2 on 2020-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_plans_current_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='eligibility',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='plans',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
