# Generated by Django 3.0.2 on 2020-01-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='No Name Provided', max_length=254)),
                ('customer_phone_number', models.CharField(default='', max_length=20)),
                ('plan', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(default='', max_length=10)),
                ('completed_status', models.BooleanField(default=False)),
                ('transaction_date', models.DateTimeField(editable=False)),
                ('customer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaction Details',
            },
        ),
    ]
