# Generated by Django 3.0.2 on 2020-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_referenceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='eligibility',
            field=models.CharField(default='', max_length=400),
        ),
    ]
