# Generated by Django 3.0.2 on 2020-01-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_onesignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='onesignal',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onesignal',
            name='type',
            field=models.CharField(default='', max_length=254),
        ),
    ]
