# Generated by Django 3.0.2 on 2020-01-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200115_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_from', models.CharField(default='', max_length=254)),
                ('title', models.CharField(default='', max_length=254)),
                ('msg', models.CharField(default='', max_length=1000)),
                ('seen', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(editable=False)),
                ('email', models.ForeignKey(default='wasche.services@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
