# Generated by Django 3.0.2 on 2020-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200116_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='image_url',
            field=models.CharField(default='No', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='No', max_length=254),
        ),
    ]
