# Generated by Django 3.0.2 on 2020-01-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_notifications_type_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='_qr_code_data',
            field=models.TextField(blank=True, db_column='qr_code_data', default=''),
        ),
    ]
