# Generated by Django 3.0.2 on 2020-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_notifications__qr_code_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='_qr_code_data',
            field=models.TextField(blank=True, db_column='qr_code_data', default=''),
        ),
    ]
