# Generated by Django 3.0.2 on 2020-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_notifications_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='image_url',
            field=models.CharField(default='No', max_length=254),
        ),
    ]
