# Generated by Django 2.2.2 on 2019-12-23 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_old_orders_overflown_orders_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_dashboard',
            name='years',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='old_orders',
            name='data',
            field=models.CharField(default='', max_length=20100),
        ),
        migrations.AlterField(
            model_name='overflown_orders_data',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='overflown_orders_data',
            name='overflown_data',
            field=models.CharField(default='', max_length=20100),
        ),
    ]
