# Generated by Django 3.0.2 on 2020-01-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191223_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Overflown_Orders_Data',
        ),
    ]
