# Generated by Django 3.0.2 on 2020-01-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_order_dashboard_total_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_dashboard',
            name='recent_date',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='order_dashboard',
            name='recent_time',
            field=models.CharField(default='', max_length=24),
        ),
    ]
