# Generated by Django 2.2.2 on 2019-12-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_removed_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscription',
            new_name='news_letter_subscription',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(default='off', max_length=4),
        ),
    ]
