# Generated by Django 3.0.2 on 2020-01-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200111_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=254)),
                ('date_created', models.DateTimeField(editable=False)),
                ('email', models.ForeignKey(default='wasche.services@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onesignal Data',
            },
        ),
    ]
