# Generated by Django 3.0.2 on 2020-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_notifications_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
