# Generated by Django 3.0.2 on 2020-01-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200116_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type_msg',
            field=models.CharField(default='notify', max_length=254),
        ),
    ]
