# Generated by Django 3.0.2 on 2020-01-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200124_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='_qr_code_data',
        ),
    ]
