# Generated by Django 3.0.2 on 2020-01-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200130_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='image_url',
            field=models.CharField(default='', max_length=254),
        ),
    ]
